import 'package:flutter/material.dart';
import 'package:qr_code_scanner/qr_code_scanner.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'dart:convert';
import 'package:http/http.dart' as http;

/// QR Configuration Screen for automatic server setup
///
/// Allows users to scan a QR code generated by Tejido backend
/// to automatically configure the server URL and connection details
class QRConfigScreen extends StatefulWidget {
  const QRConfigScreen({Key? key}) : super(key: key);

  @override
  State<QRConfigScreen> createState() => _QRConfigScreenState();
}

class _QRConfigScreenState extends State<QRConfigScreen> {
  final GlobalKey qrKey = GlobalKey(debugLabel: 'QR');
  QRViewController? controller;
  bool isProcessing = false;

  @override
  void reassemble() {
    super.reassemble();
    if (controller != null) {
      controller!.pauseCamera();
      controller!.resumeCamera();
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Configurar con QR'),
        backgroundColor: Colors.teal,
        elevation: 0,
      ),
      body: Column(
        children: [
          // Instrucciones
          Container(
            padding: const EdgeInsets.all(16),
            color: Colors.blue.shade50,
            child: Row(
              children: [
                Icon(Icons.qr_code_scanner, size: 40, color: Colors.blue.shade700),
                const SizedBox(width: 12),
                Expanded(
                  child: Text(
                    'Apunta la cámara hacia el código QR generado por Tejido',
                    style: TextStyle(
                      fontSize: 14,
                      color: Colors.blue.shade900,
                      fontWeight: FontWeight.w500,
                    ),
                  ),
                ),
              ],
            ),
          ),

          // Visor de cámara QR
          Expanded(
            flex: 5,
            child: QRView(
              key: qrKey,
              onQRViewCreated: _onQRViewCreated,
              overlay: QrScannerOverlayShape(
                borderColor: Colors.teal,
                borderRadius: 10,
                borderLength: 30,
                borderWidth: 10,
                cutOutSize: MediaQuery.of(context).size.width * 0.8,
              ),
            ),
          ),

          // Estado de procesamiento
          if (isProcessing)
            Container(
              padding: const EdgeInsets.all(20),
              child: Column(
                children: const [
                  CircularProgressIndicator(color: Colors.teal),
                  SizedBox(height: 12),
                  Text(
                    'Configurando conexión...',
                    style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold),
                  ),
                ],
              ),
            ),

          // Información adicional
          if (!isProcessing)
            Container(
              padding: const EdgeInsets.all(16),
              color: Colors.grey.shade100,
              child: Column(
                children: [
                  Icon(Icons.info_outline, color: Colors.grey.shade700, size: 28),
                  const SizedBox(height: 8),
                  Text(
                    'El código QR contiene la URL del servidor Tejido',
                    style: TextStyle(
                      fontSize: 13,
                      color: Colors.grey.shade700,
                    ),
                    textAlign: TextAlign.center,
                  ),
                  const SizedBox(height: 4),
                  Text(
                    'Luego de escanear, podrás iniciar sesión',
                    style: TextStyle(
                      fontSize: 12,
                      color: Colors.grey.shade600,
                    ),
                    textAlign: TextAlign.center,
                  ),
                ],
              ),
            ),
        ],
      ),
    );
  }

  void _onQRViewCreated(QRViewController controller) {
    this.controller = controller;

    controller.scannedDataStream.listen((scanData) {
      if (!isProcessing && scanData.code != null) {
        _processQRData(scanData.code!);
      }
    });
  }

  Future<void> _processQRData(String qrData) async {
    setState(() => isProcessing = true);

    try {
      // DEBUG: Mostrar QR escaneado
      print('═══ QR CONFIG DEBUG ═══');
      print('QR Data: $qrData');

      // 1. Decodificar JSON del QR
      final config = json.decode(qrData) as Map<String, dynamic>;
      print('Config decodificado: $config');

      // 2. Validar estructura
      if (!config.containsKey('server_url')) {
        throw Exception('QR inválido: falta server_url');
      }

      final serverUrl = config['server_url'] as String;
      final serverName = config['server_name'] as String? ?? 'Tejido';

      print('Server URL: $serverUrl');
      print('Server Name: $serverName');
      print('Endpoint completo: $serverUrl/api/');

      // 3. Probar conexión al servidor (con reintentos)
      http.Response? testResponse;
      int attempts = 0;
      const maxAttempts = 3;
      Exception? lastError;

      while (attempts < maxAttempts) {
        attempts++;
        print('\n--- Intento $attempts de $maxAttempts ---');
        print('Conectando a: $serverUrl/api/');
        print('Tiempo: ${DateTime.now()}');

        try {
          final startTime = DateTime.now();
          testResponse = await http.get(
            Uri.parse('$serverUrl/api/'),
          ).timeout(const Duration(seconds: 30)); // Timeout aumentado a 30s

          final duration = DateTime.now().difference(startTime);
          print('Respuesta recibida en: ${duration.inMilliseconds}ms');
          print('Status code: ${testResponse.statusCode}');
          print('Headers: ${testResponse.headers}');

          if (testResponse.statusCode == 302 || testResponse.statusCode == 200) {
            print('✅ Conexión exitosa!');
            break; // Conexión exitosa
          } else {
            print('⚠️  Status code inesperado: ${testResponse.statusCode}');
            lastError = Exception('Servidor respondió con código ${testResponse.statusCode}');
          }
        } catch (e) {
          print('❌ Error en intento $attempts:');
          print('Tipo de error: ${e.runtimeType}');
          print('Mensaje: $e');
          lastError = e is Exception ? e : Exception(e.toString());
          if (attempts < maxAttempts) {
            print('Esperando 2 segundos antes de reintentar...');
            await Future.delayed(const Duration(seconds: 2)); // Esperar 2s antes de reintentar
          }
        }
      }

      print('\n--- Resultado Final ---');
      if (testResponse == null || (testResponse.statusCode != 302 && testResponse.statusCode != 200)) {
        print('❌ Falló después de $maxAttempts intentos');
        print('Último error: $lastError');
        throw lastError ?? Exception('No se pudo conectar al servidor después de $maxAttempts intentos');
      }

      print('✅ Configuración exitosa');
      print('═══ FIN DEBUG ═══\n');

      // 4. Guardar configuración
      final prefs = await SharedPreferences.getInstance();
      await prefs.setString('server_url', serverUrl);
      await prefs.setString('server_name', serverName);
      await prefs.setBool('is_configured', true);

      // 5. Mostrar éxito y redirigir
      if (mounted) {
        controller?.pauseCamera();

        await showDialog(
          context: context,
          barrierDismissible: false,
          builder: (context) => AlertDialog(
            title: Row(
              children: const [
                Icon(Icons.check_circle, color: Colors.green, size: 32),
                SizedBox(width: 12),
                Text('¡Configuración Exitosa!'),
              ],
            ),
            content: Column(
              mainAxisSize: MainAxisSize.min,
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text('Servidor: $serverName'),
                const SizedBox(height: 8),
                Text(
                  'URL: $serverUrl',
                  style: TextStyle(
                    fontFamily: 'monospace',
                    fontSize: 12,
                    color: Colors.grey.shade700,
                  ),
                ),
                const SizedBox(height: 16),
                const Text(
                  'Ahora puedes iniciar sesión con tus credenciales',
                  style: TextStyle(fontSize: 14),
                ),
              ],
            ),
            actions: [
              ElevatedButton(
                onPressed: () {
                  Navigator.of(context).pop(); // Cerrar diálogo
                  Navigator.of(context).pop(); // Volver a login
                },
                style: ElevatedButton.styleFrom(
                  backgroundColor: Colors.teal,
                  padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 12),
                ),
                child: const Text('Continuar al Login'),
              ),
            ],
          ),
        );
      }
    } catch (e) {
      // Error: mostrar mensaje
      if (mounted) {
        controller?.pauseCamera();

        await showDialog(
          context: context,
          builder: (context) => AlertDialog(
            title: Row(
              children: const [
                Icon(Icons.error, color: Colors.red, size: 32),
                SizedBox(width: 12),
                Expanded(child: Text('Error de Configuración')),
              ],
            ),
            content: Column(
              mainAxisSize: MainAxisSize.min,
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                const Text(
                  'No se pudo configurar la conexión:',
                  style: TextStyle(fontWeight: FontWeight.bold),
                ),
                const SizedBox(height: 12),
                Text(
                  e.toString(),
                  style: const TextStyle(fontSize: 13, color: Colors.red),
                ),
                const SizedBox(height: 16),
                const Text(
                  'Verifica que:',
                  style: TextStyle(fontWeight: FontWeight.bold),
                ),
                const SizedBox(height: 8),
                const Text('• El QR proviene de Tejido', style: TextStyle(fontSize: 13)),
                const Text('• El servidor está activo', style: TextStyle(fontSize: 13)),
                const Text('• Estás conectado a la misma red WiFi', style: TextStyle(fontSize: 13)),
              ],
            ),
            actions: [
              TextButton(
                onPressed: () {
                  Navigator.of(context).pop();
                  setState(() => isProcessing = false);
                  controller?.resumeCamera();
                },
                child: const Text('Intentar de nuevo'),
              ),
              TextButton(
                onPressed: () {
                  Navigator.of(context).pop();
                  Navigator.of(context).pop(); // Volver a login
                },
                child: const Text('Cancelar'),
              ),
            ],
          ),
        );
      }
    }
  }

  @override
  void dispose() {
    controller?.dispose();
    super.dispose();
  }
}
